import assert from "node:assert/strict";
import { Buffer } from "node:buffer";
import { createHash } from "node:crypto";
import { readFile } from "node:fs/promises";
import test from "node:test";

import {
  isCanonicalProductImageObjectPath,
  isEligibleProductImageOrphan,
} from "../../scripts/admin/task-137-product-image-cleanup.mjs";
import {
  downloadProductImageWithOneAuthRefresh,
  safeProductImageStorageUrl,
} from "../../src/lib/product-images/browser-client.ts";
import { inspectInputImageHeader } from "../../src/lib/product-images/input-dimensions.ts";
import {
  PRODUCT_IMAGE_MAIN_MAX_BYTES,
  PRODUCT_IMAGE_READ_BATCH_LIMIT,
  PRODUCT_IMAGE_THUMB_MAX_BYTES,
  parseProductImageFinalizeInput,
  parseProductImageIntentInput,
  parseProductImageReadInput,
  parseProductImageRemoveInput,
  readProductImageJson,
} from "../../src/server/shop-admin/product-images/contract.ts";
import { inspectJpeg } from "../../src/server/shop-admin/product-images/jpeg-validator.ts";

const SHOP_ID = "10000000-0000-4000-8000-000000000137";
const PRODUCT_ID = "20000000-0000-4000-8000-000000000137";
const VERSION_ID = "30000000-0000-4000-8000-000000000137";
// Generated by libvips/sharp from a 2x3 / 4x5 RGB buffer.  These fixture
// bytes are decodable JPEGs, unlike the compact malformed-byte fixtures below.
const BASELINE_JPEG = Uint8Array.from(
  Buffer.from(
    "/9j/2wBDAAMCAgMCAgMDAwMEAwMEBQgFBQQEBQoHBwYIDAoMDAsKCwsNDhIQDQ4RDgsLEBYQERMUFRUVDA8XGBYUGBIUFRT/2wBDAQMEBAUEBQkFBQkUDQsNFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBT/wAARCAADAAIDASIAAhEBAxEB/8QAFQABAQAAAAAAAAAAAAAAAAAAAAn/xAAUEAEAAAAAAAAAAAAAAAAAAAAA/8QAFAEBAAAAAAAAAAAAAAAAAAAABv/EABQRAQAAAAAAAAAAAAAAAAAAAAD/2gAMAwEAAhEDEQA/AJ9AFA4//9k=",
    "base64",
  ),
);
const PROGRESSIVE_JPEG = Uint8Array.from(
  Buffer.from(
    "/9j/2wBDAAMCAgMCAgMDAwMEAwMEBQgFBQQEBQoHBwYIDAoMDAsKCwsNDhIQDQ4RDgsLEBYQERMUFRUVDA8XGBYUGBIUFRT/2wBDAQMEBAUEBQkFBQkUDQsNFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBT/wgARCAAFAAQDASIAAhEBAxEB/8QAFQABAQAAAAAAAAAAAAAAAAAAAAf/xAAVAQEBAAAAAAAAAAAAAAAAAAAABv/aAAwDAQACEAMQAAABngjX/8QAFBABAAAAAAAAAAAAAAAAAAAAAP/aAAgBAQABBQJ//8QAFBEBAAAAAAAAAAAAAAAAAAAAAP/aAAgBAwEBPwF//8QAFBEBAAAAAAAAAAAAAAAAAAAAAP/aAAgBAgEBPwF//8QAFBABAAAAAAAAAAAAAAAAAAAAAP/aAAgBAQAGPwJ//8QAFBABAAAAAAAAAAAAAAAAAAAAAP/aAAgBAQABPyF//9oADAMBAAIAAwAAABD7/8QAFBEBAAAAAAAAAAAAAAAAAAAAAP/aAAgBAwEBPxB//8QAFBEBAAAAAAAAAAAAAAAAAAAAAP/aAAgBAgEBPxB//8QAFBABAAAAAAAAAAAAAAAAAAAAAP/aAAgBAQABPxB//9k=",
    "base64",
  ),
);

function copyBytes(bytes) {
  return Uint8Array.from(bytes);
}

function markerOffset(bytes, marker) {
  for (let index = 2; index < bytes.length - 1; index += 1) {
    if (bytes[index] === 0xff && bytes[index + 1] === marker) return index;
  }
  return -1;
}

function insertAfterSoi(bytes, segment) {
  return Uint8Array.from([...bytes.slice(0, 2), ...segment, ...bytes.slice(2)]);
}

function replaceSegment(bytes, offset, replacement) {
  const originalLength = (bytes[offset + 2] << 8) | bytes[offset + 3];
  return Uint8Array.from([
    ...bytes.slice(0, offset),
    ...replacement,
    ...bytes.slice(offset + 2 + originalLength),
  ]);
}

function jpeg(width, height, options = {}) {
  const frameMarker = options.progressive ? 0xc2 : 0xc0;
  const app1 = options.app1
    ? [0xff, 0xe1, 0x00, 0x08, 0x45, 0x78, 0x69, 0x66, 0x00, 0x00]
    : [];
  const scanBytes = options.multiScan
    ? [
        0x01,
        0x02,
        0xff,
        0xd0,
        0x03,
        0xff,
        0xda,
        0x00,
        0x08,
        0x01,
        0x01,
        0x00,
        0x00,
        0x3f,
        0x00,
        0x04,
        0xff,
        0x00,
        0x05,
      ]
    : [0x01, 0x02, 0xff, 0x00, 0x03];
  return Uint8Array.from([
    0xff,
    0xd8,
    ...app1,
    ...(options.segments ?? []).flat(),
    0xff,
    frameMarker,
    0x00,
    0x0b,
    0x08,
    (height >> 8) & 0xff,
    height & 0xff,
    (width >> 8) & 0xff,
    width & 0xff,
    0x01,
    0x01,
    0x11,
    0x00,
    0xff,
    0xda,
    0x00,
    0x08,
    0x01,
    0x01,
    0x00,
    0x00,
    0x3f,
    0x00,
    ...scanBytes,
    0xff,
    0xd9,
    ...(options.trailingBytes ?? []),
  ]);
}

function validIntent() {
  return {
    main: {
      bytes: 700_000,
      height: 1200,
      mimeType: "image/jpeg",
      sha256: "a".repeat(64),
      width: 1600,
    },
    productId: PRODUCT_ID,
    shopId: SHOP_ID,
    thumb: {
      bytes: 90_000,
      height: 288,
      mimeType: "image/jpeg",
      sha256: "b".repeat(64),
      width: 384,
    },
  };
}

test("TASK-137 JPEG parser accepts real baseline and progressive JPEG fixtures", () => {
  assert.deepEqual(inspectJpeg(BASELINE_JPEG), {
    inspection: { height: 3, width: 2 },
    ok: true,
  });
  assert.deepEqual(inspectJpeg(PROGRESSIVE_JPEG), {
    inspection: { height: 5, width: 4 },
    ok: true,
  });
});

test("TASK-137 JPEG parser rejects APP1 metadata", () => {
  assert.deepEqual(inspectJpeg(jpeg(800, 600, { app1: true })), {
    code: "jpeg_metadata_forbidden",
    ok: false,
  });
});

test("TASK-137 JPEG parser permits only canonical JFIF APP0 and no metadata carriers", () => {
  const jfif = [
    0xff,
    0xe0,
    0x00,
    0x10,
    0x4a,
    0x46,
    0x49,
    0x46,
    0x00,
    0x01,
    0x01,
    0x00,
    0x00,
    0x01,
    0x00,
    0x01,
    0x00,
    0x00,
  ];
  const comment = [0xff, 0xfe, 0x00, 0x04, 0x6f, 0x6b];
  const jfxx = [0xff, 0xe0, 0x00, 0x07, 0x4a, 0x46, 0x58, 0x58, 0x00];
  const icc = [0xff, 0xe2, 0x00, 0x04, 0x49, 0x43];
  const jfifWithThumbnail = [
    ...jfif.slice(0, 2),
    0x00,
    0x13,
    ...jfif.slice(4, 16),
    0x01,
    0x01,
    0x00,
    0x00,
    0x00,
  ];

  assert.equal(inspectJpeg(insertAfterSoi(BASELINE_JPEG, jfif)).ok, true);
  for (const segment of [comment, jfxx, icc, jfifWithThumbnail]) {
    assert.deepEqual(inspectJpeg(insertAfterSoi(BASELINE_JPEG, segment)), {
      code: "jpeg_metadata_forbidden",
      ok: false,
    });
  }
});

test("TASK-137 JPEG parser requires the exact two-byte DRI restart interval", () => {
  const validDri = [0xff, 0xdd, 0x00, 0x04, 0x00, 0x00];
  const malformedDriSegments = [
    [0xff, 0xdd, 0x00, 0x02],
    [0xff, 0xdd, 0x00, 0x03, 0x00],
    [0xff, 0xdd, 0x00, 0x05, 0x00, 0x00, 0x00],
  ];

  assert.equal(inspectJpeg(insertAfterSoi(BASELINE_JPEG, validDri)).ok, true);
  for (const segment of malformedDriSegments) {
    assert.deepEqual(inspectJpeg(insertAfterSoi(BASELINE_JPEG, segment)), {
      code: "jpeg_structure_invalid",
      ok: false,
    });
  }
});

test("TASK-137 JPEG parser requires a canonical scan and frame state", () => {
  const noScanOffset = markerOffset(BASELINE_JPEG, 0xda);
  const noScan = Uint8Array.from([
    ...BASELINE_JPEG.slice(0, noScanOffset),
    0xff,
    0xd9,
  ]);
  const losslessFrame = copyBytes(BASELINE_JPEG);
  const frameOffset = markerOffset(losslessFrame, 0xc0);
  losslessFrame[frameOffset + 1] = 0xc3;
  const nestedSoi = insertAfterSoi(BASELINE_JPEG, [0xff, 0xd8]);
  const malformedScan = copyBytes(BASELINE_JPEG);
  const scanOffset = markerOffset(malformedScan, 0xda);
  malformedScan[scanOffset + 2] = 0x00;
  malformedScan[scanOffset + 3] = 0x02;
  const frameAfterScan = Uint8Array.from([
    ...BASELINE_JPEG.slice(0, -2),
    0xff,
    0xc0,
    0x00,
    0x0b,
    0x08,
    0x00,
    0x03,
    0x00,
    0x02,
    0x01,
    0x01,
    0x11,
    0x00,
    0xff,
    0xd9,
  ]);

  for (const malformed of [
    jpeg(800, 600),
    noScan,
    losslessFrame,
    nestedSoi,
    malformedScan,
    frameAfterScan,
  ]) {
    assert.deepEqual(inspectJpeg(malformed), {
      code: "jpeg_structure_invalid",
      ok: false,
    });
  }
  assert.deepEqual(
    inspectJpeg(Uint8Array.from([...BASELINE_JPEG, 0xff, 0xd9])),
    { code: "jpeg_structure_invalid", ok: false },
  );
});

test("TASK-137 JPEG parser rejects malformed Huffman trees and missing table bindings", () => {
  const firstDhtOffset = markerOffset(BASELINE_JPEG, 0xc4);
  const sofOffset = markerOffset(BASELINE_JPEG, 0xc0);
  const sosOffset = markerOffset(BASELINE_JPEG, 0xda);
  assert.notEqual(firstDhtOffset, -1);
  assert.notEqual(sofOffset, -1);
  assert.notEqual(sosOffset, -1);

  const oversubscribedDht = replaceSegment(BASELINE_JPEG, firstDhtOffset, [
    0xff,
    0xc4,
    0x00,
    0x16,
    0x00,
    0x03,
    ...Array(15).fill(0),
    0x00,
    0x09,
    0x0a,
  ]);
  const allOnesDht = copyBytes(BASELINE_JPEG);
  allOnesDht[firstDhtOffset + 5] = 0x02;
  allOnesDht[firstDhtOffset + 6] = 0x00;
  const missingDcTable = copyBytes(BASELINE_JPEG);
  missingDcTable[firstDhtOffset + 4] = 0x10;
  const missingQuantizationTable = copyBytes(BASELINE_JPEG);
  missingQuantizationTable[sofOffset + 12] = 0x03;

  for (const malformed of [
    oversubscribedDht,
    allOnesDht,
    missingDcTable,
    missingQuantizationTable,
  ]) {
    assert.deepEqual(inspectJpeg(malformed), {
      code: "jpeg_structure_invalid",
      ok: false,
    });
  }

  for (const selector of [0x22, 0xf0]) {
    const malformedSelector = copyBytes(BASELINE_JPEG);
    malformedSelector[sosOffset + 6] = selector;
    assert.deepEqual(inspectJpeg(malformedSelector), {
      code: "jpeg_structure_invalid",
      ok: false,
    });
  }
});

test("TASK-137 JPEG parser rejects invalid magic and trailing bytes", () => {
  assert.equal(inspectJpeg(Uint8Array.from([1, 2, 3, 4])).ok, false);
  const withTrailingByte = Uint8Array.from([...jpeg(800, 600), 0x00]);
  assert.deepEqual(inspectJpeg(withTrailingByte), {
    code: "jpeg_magic_invalid",
    ok: false,
  });
});

test("TASK-137 intent parser freezes budgets and aspect ratio", () => {
  assert.deepEqual(parseProductImageIntentInput(validIntent()), validIntent());

  const oversizedMain = validIntent();
  oversizedMain.main.bytes = PRODUCT_IMAGE_MAIN_MAX_BYTES + 1;
  assert.equal(parseProductImageIntentInput(oversizedMain), null);

  const oversizedThumb = validIntent();
  oversizedThumb.thumb.bytes = PRODUCT_IMAGE_THUMB_MAX_BYTES + 1;
  assert.equal(parseProductImageIntentInput(oversizedThumb), null);

  const wrongAspect = validIntent();
  wrongAspect.thumb.height = 384;
  assert.equal(parseProductImageIntentInput(wrongAspect), null);
});

test("TASK-137 parser rejects non-JPEG metadata and malformed hashes", () => {
  const png = validIntent();
  png.main.mimeType = "image/png";
  assert.equal(parseProductImageIntentInput(png), null);

  const uppercaseHash = validIntent();
  uppercaseHash.main.sha256 = "A".repeat(64);
  assert.equal(parseProductImageIntentInput(uppercaseHash), null);
});

test("TASK-137 finalize and remove require opaque UUIDs", () => {
  assert.deepEqual(
    parseProductImageFinalizeInput({
      productId: PRODUCT_ID,
      shopId: SHOP_ID,
      versionId: VERSION_ID,
    }),
    { productId: PRODUCT_ID, shopId: SHOP_ID, versionId: VERSION_ID },
  );
  assert.deepEqual(
    parseProductImageRemoveInput({
      expectedVersionId: VERSION_ID,
      productId: PRODUCT_ID,
      shopId: SHOP_ID,
    }),
    {
      expectedVersionId: VERSION_ID,
      productId: PRODUCT_ID,
      shopId: SHOP_ID,
      versionId: VERSION_ID,
    },
  );
  assert.equal(
    parseProductImageFinalizeInput({
      productId: PRODUCT_ID,
      shopId: SHOP_ID,
      versionId: "product-name",
    }),
    null,
  );
});

test("TASK-137 read contract is bounded to private references", () => {
  const ref = { productId: PRODUCT_ID, variant: "thumb", versionId: VERSION_ID };
  assert.equal(
    parseProductImageReadInput({
      refs: Array.from({ length: PRODUCT_IMAGE_READ_BATCH_LIMIT }, () => ref),
      shopId: SHOP_ID,
    })?.refs.length,
    PRODUCT_IMAGE_READ_BATCH_LIMIT,
  );
  assert.equal(
    parseProductImageReadInput({
      refs: Array.from({ length: PRODUCT_IMAGE_READ_BATCH_LIMIT + 1 }, () => ref),
      shopId: SHOP_ID,
    }),
    null,
  );
});

test("TASK-137 bounded JSON reader rejects wrong media type and oversized bodies", async () => {
  assert.equal(
    await readProductImageJson(
      new Request("http://localhost/api", {
        body: "{}",
        headers: { "content-type": "text/plain" },
        method: "POST",
      }),
    ),
    null,
  );

  assert.equal(
    await readProductImageJson(
      new Request("http://localhost/api", {
        body: JSON.stringify({ payload: "x".repeat(20_000) }),
        headers: { "content-type": "application/json" },
        method: "POST",
      }),
    ),
    null,
  );
});

test("TASK-137 migration keeps Storage private and RPCs service-only", async () => {
  const [migration, cleanupHardening, deniedAuditGuard] = await Promise.all([
    readFile(
      new URL(
        "../../supabase/migrations/20260717072959_task_137_product_catalog_images.sql",
        import.meta.url,
      ),
      "utf8",
    ),
    readFile(
      new URL(
        "../../supabase/migrations/20260717170000_task_137_product_image_cleanup_hardening.sql",
        import.meta.url,
      ),
      "utf8",
    ),
    readFile(
      new URL(
        "../../supabase/migrations/20260717200129_task_137_product_image_denied_audit_guard.sql",
        import.meta.url,
      ),
      "utf8",
    ),
  ]);

  assert.match(migration, /'product-images',[\s\S]*?false,[\s\S]*?1048576/);
  assert.match(
    migration,
    /create policy task137_product_images_private_read[\s\S]*?for select[\s\S]*?to authenticated/,
  );
  assert.doesNotMatch(
    migration,
    /create policy task137_product_images[^;]*?for (insert|update|delete|all)/i,
  );
  assert.match(
    migration,
    /grant execute on function public\.product_image_create_intent[^;]+to service_role/,
  );
  assert.match(
    migration,
    /revoke all on function public\.product_image_create_intent[^;]+from public, anon, authenticated/,
  );
  assert.match(cleanupHardening, /product_image_prepare_cleanup/);
  assert.match(cleanupHardening, /primary_image_version_id = p_version_id/);
  assert.match(cleanupHardening, /now\(\) - interval '24 hours'/);
  assert.match(cleanupHardening, /product_image_record_orphan_cleanup/);
  assert.match(
    cleanupHardening,
    /grant execute on function public\.product_image_prepare_cleanup[^;]+to service_role/,
  );
  assert.doesNotMatch(cleanupHardening, /signed_url|upload_url|main_path'.*metadata/i);
  const actorGuard = deniedAuditGuard.indexOf(
    "app_private.product_image_actor_can_read",
  );
  const productGuard = deniedAuditGuard.indexOf(
    "app_private.product_image_product_is_in_shop",
  );
  const auditSink = deniedAuditGuard.indexOf(
    "app_private.write_product_image_audit",
  );
  assert.match(
    deniedAuditGuard,
    /security definer[\s\S]*set search_path = public, app_private, pg_temp/,
  );
  assert.match(deniedAuditGuard, /coalesce\(auth\.role\(\), ''\) <> 'service_role'/);
  assert.match(
    deniedAuditGuard,
    /grant select on table[\s\S]*public\.profiles,[\s\S]*public\.shops,[\s\S]*public\.shop_members,[\s\S]*public\.platform_admins[\s\S]*to service_role/,
  );
  assert.ok(actorGuard >= 0 && actorGuard < auditSink);
  assert.ok(productGuard >= 0 && productGuard < auditSink);
  assert.match(
    deniedAuditGuard,
    /revoke all on function public\.product_image_record_denied[\s\S]*from public, anon, authenticated/,
  );
  assert.match(
    deniedAuditGuard,
    /grant execute on function public\.product_image_record_denied[\s\S]*to service_role/,
  );
});

test("TASK-137 sync payload contains product IDs but no object path or URL", async () => {
  const migration = await readFile(
    new URL(
      "../../supabase/migrations/20260717073607_task_137_product_catalog_images_sync_fix.sql",
      import.meta.url,
    ),
    "utf8",
  );
  const syncFunction = migration.slice(
    migration.indexOf("create or replace function app_private.emit_product_image_sync_event"),
  );

  assert.match(syncFunction, /jsonb_build_object\('product_ids'/);
  assert.match(syncFunction, /'catalog_changed'/);
  assert.doesNotMatch(syncFunction, /main_path|thumb_path|signed_url|upload_url|token/);
});

test("TASK-137 routes are no-store and never accept image bytes", async () => {
  const contract = await readFile(
    new URL(
      "../../src/server/shop-admin/product-images/contract.ts",
      import.meta.url,
    ),
    "utf8",
  );
  const routes = await Promise.all(
    ["intent", "finalize", "read-urls", "remove"].map((route) =>
      readFile(
        new URL(
          `../../src/app/api/shop/product-images/${route}/route.ts`,
          import.meta.url,
        ),
        "utf8",
      ),
    ),
  );

  assert.match(contract, /"Cache-Control": "no-store"/);
  for (const route of routes) {
    assert.match(route, /readProductImageJson/);
    assert.match(route, /recordProductImageDenied/);
    assert.doesNotMatch(route, /formData\(|arrayBuffer\(|File\b|Blob\b/);
  }
  assert.match(routes[0], /operation: "intent"/);
  assert.match(routes[1], /operation: "finalize"/);
  assert.match(routes[2], /operation: "read"/);
  assert.match(routes[3], /operation: "remove"/);
});

test("TASK-139 shared image contract fixes batch 16 and nested ready metadata", async () => {
  const contractBytes = await readFile(
    new URL("../../contracts/product-image-v1.json", import.meta.url),
  );
  const contract = JSON.parse(contractBytes.toString("utf8"));
  const sidecar = await readFile(
    new URL("../../contracts/product-image-v1.sha256", import.meta.url),
    "utf8",
  );
  const hash = createHash("sha256").update(contractBytes).digest("hex");

  assert.equal(contract.limits.readBatchMaximum, 16);
  assert.deepEqual(contract.api.readUrls.itemRequired, [
    "productId",
    "status",
    "variant",
    "versionId",
  ]);
  assert.deepEqual(contract.api.readUrls.itemRequiredByStatus, {
    not_found: [],
    ready: ["expiresAt", "metadata", "signedUrl"],
  });
  assert.deepEqual(contract.api.readUrls.itemMetadataRequired, [
    "bytes",
    "height",
    "mimeType",
    "sha256",
    "width",
  ]);
  assert.match(
    sidecar,
    new RegExp(`^${hash}  contracts/product-image-v1.json`, "m"),
  );
});

test("TASK-137 and preserved POS reads enforce their requested permission", async () => {
  const [dataAccess, inventoryReadModel, permissions, posRoute, staffPermissions] =
    await Promise.all([
      readFile(
        new URL("../../src/server/shop-admin/data-access.ts", import.meta.url),
        "utf8",
      ),
      readFile(
        new URL(
          "../../src/server/shop-admin/inventory-read-model.ts",
          import.meta.url,
        ),
        "utf8",
      ),
      readFile(
        new URL("../../src/server/shop-admin/permissions.ts", import.meta.url),
        "utf8",
      ),
      readFile(
        new URL(
          "../../src/app/api/shop/pos/revenue/sale-detail/route.ts",
          import.meta.url,
        ),
        "utf8",
      ),
      readFile(
        new URL(
          "../../src/server/shop-admin/staff-web-permissions.ts",
          import.meta.url,
        ),
        "utf8",
      ),
    ]);

  assert.match(inventoryReadModel, /requiredPermission: "products\.read"/);
  assert.match(posRoute, /requiredPermission: "pos\.dashboard\.read"/);
  assert.match(dataAccess, /requiredPermission\?: ShopAdminPermission/);
  assert.match(dataAccess, /canShopAdmin\(access\.selectedShop\.role/);
  assert.match(dataAccess, /canStaffWebPerformShopAdminAction\(/);
  assert.match(dataAccess, /status: "unauthorized"/);
  assert.match(permissions, /\| "pos\.dashboard\.read"/);
  assert.match(
    staffPermissions,
    /permission === "pos\.dashboard\.read"[\s\S]*return "pos\.dashboard\.read"/,
  );
});

test("TASK-137 server never logs signed URLs, tokens or image bytes", async () => {
  const service = await readFile(
    new URL(
      "../../src/server/shop-admin/product-images/service.ts",
      import.meta.url,
    ),
    "utf8",
  );
  assert.doesNotMatch(service, /console\.(log|info|warn|error)/);
  assert.doesNotMatch(service, /metadata_redacted[^\n]*(signed|token|path)/i);
});

test("TASK-137 browser pipeline freezes preprocessing, direct PUT and account-scoped byte cache", async () => {
  const client = await readFile(
    new URL(
      "../../src/lib/product-images/browser-client.ts",
      import.meta.url,
    ),
    "utf8",
  );

  assert.match(client, /const MAIN_MAX_SIDE = 1600/);
  assert.match(client, /const MAIN_TARGET_BYTES = 750 \* 1024/);
  assert.match(client, /const MAIN_MAX_BYTES = 1024 \* 1024/);
  assert.match(client, /const THUMB_MAX_SIDE = 384/);
  assert.match(client, /const THUMB_MAX_BYTES = 90 \* 1024/);
  assert.match(client, /qualities: \[0\.82, 0\.76, 0\.7\]/);
  assert.match(client, /minimumSide: 640/);
  assert.match(client, /minimumSide: 128/);
  assert.match(
    client,
    /const OUTPUT_SIDE_FACTORS = \[1, 0\.85, 0\.72, 0\.61, 0\.52, 0\.44, 0\.4\] as const/,
  );
  assert.match(
    client,
    /OUTPUT_SIDE_FACTORS\.map\(\(factor\) =>[\s\S]*Math\.floor\(maximum \* factor\)/,
  );
  assert.match(client, /PRODUCT_IMAGE_PREPROCESS_MEASURE/);
  assert.match(client, /performance\.measure\(PRODUCT_IMAGE_PREPROCESS_MEASURE/);
  assert.match(client, /context\.fillStyle = "#ffffff"/);
  assert.match(client, /crypto\.subtle\.digest\(\s*"SHA-256"/);
  assert.match(client, /const body = new FormData\(\)/);
  assert.match(client, /method: "PUT"/);
  assert.match(client, /"x-upsert": "false"/);
  assert.match(
    client,
    /cacheScope,[\s\S]*?ref\.shopId,[\s\S]*?ref\.productId,[\s\S]*?ref\.versionId,[\s\S]*?`\$\{ref\.variant\}\.jpg`/,
  );
  assert.doesNotMatch(client, /localStorage|sessionStorage/);
  assert.doesNotMatch(client, /console\.(log|info|warn|error)/);
});

test("TASK-139 rejects oversized raster dimensions before browser decode", () => {
  const png = (width, height) =>
    Uint8Array.from([
      0x89, 0x50, 0x4e, 0x47, 0x0d, 0x0a, 0x1a, 0x0a,
      0x00, 0x00, 0x00, 0x0d, 0x49, 0x48, 0x44, 0x52,
      (width >>> 24) & 0xff, (width >>> 16) & 0xff,
      (width >>> 8) & 0xff, width & 0xff,
      (height >>> 24) & 0xff, (height >>> 16) & 0xff,
      (height >>> 8) & 0xff, height & 0xff,
    ]);
  const jpeg = (width, height) =>
    Uint8Array.from([
      0xff, 0xd8,
      0xff, 0xc0, 0x00, 0x11, 0x08,
      (height >>> 8) & 0xff, height & 0xff,
      (width >>> 8) & 0xff, width & 0xff,
      0x03, 0x01, 0x11, 0x00, 0x02, 0x11, 0x00, 0x03, 0x11, 0x00,
    ]);

  assert.deepEqual(
    inspectInputImageHeader(png(8_000, 8_000), "image/png", 64_000_000),
    { height: 8_000, width: 8_000 },
  );
  assert.equal(
    inspectInputImageHeader(png(8_001, 8_000), "image/png", 64_000_000),
    null,
  );
  assert.equal(
    inspectInputImageHeader(jpeg(10_000, 10_000), "image/jpeg", 64_000_000),
    null,
  );
});

test("TASK-137 signed Storage URLs stay bound to the configured Supabase origin", () => {
  const previousSupabaseUrl = process.env.NEXT_PUBLIC_SUPABASE_URL;
  const previousWindow = globalThis.window;
  process.env.NEXT_PUBLIC_SUPABASE_URL = "https://project-137.supabase.co";
  globalThis.window = { location: { origin: "https://admin.task137.invalid" } };

  try {
    const canonicalPath = `shops/${SHOP_ID}/products/${PRODUCT_ID}/primary/${VERSION_ID}/main.jpg`;
    assert.equal(
      safeProductImageStorageUrl(
        `https://project-137.supabase.co/storage/v1/object/sign/product-images/${canonicalPath}?token=redacted`,
        "read",
        {
          productId: PRODUCT_ID,
          shopId: SHOP_ID,
          variant: "main",
          versionId: VERSION_ID,
        },
      ),
      `https://project-137.supabase.co/storage/v1/object/sign/product-images/${canonicalPath}?token=redacted`,
    );
    assert.throws(
      () =>
        safeProductImageStorageUrl(
          `https://attacker.invalid/storage/v1/object/sign/product-images/${canonicalPath}?token=redacted`,
          "read",
          {
            productId: PRODUCT_ID,
            shopId: SHOP_ID,
            variant: "main",
            versionId: VERSION_ID,
          },
        ),
      /image_signed_url_invalid/,
    );
    assert.throws(
      () =>
        safeProductImageStorageUrl(
          "https://project-137.supabase.co/redirect/storage/v1/object/sign/product-images/path.jpg",
          "read",
          {
            productId: PRODUCT_ID,
            shopId: SHOP_ID,
            variant: "main",
            versionId: VERSION_ID,
          },
        ),
      /image_signed_url_invalid/,
    );
    assert.throws(
      () =>
        safeProductImageStorageUrl(
          `https://project-137.supabase.co/storage/v1/object/sign/product-images/shops/${SHOP_ID}/products/${PRODUCT_ID}/primary/${VERSION_ID}/../main.jpg?token=redacted`,
          "read",
          {
            productId: PRODUCT_ID,
            shopId: SHOP_ID,
            variant: "main",
            versionId: VERSION_ID,
          },
        ),
      /image_signed_url_invalid/,
    );
  } finally {
    if (previousSupabaseUrl === undefined) {
      delete process.env.NEXT_PUBLIC_SUPABASE_URL;
    } else {
      process.env.NEXT_PUBLIC_SUPABASE_URL = previousSupabaseUrl;
    }
    if (previousWindow === undefined) {
      delete globalThis.window;
    } else {
      globalThis.window = previousWindow;
    }
  }
});

test("TASK-137 signed read refreshes once only after Storage auth expiry", async () => {
  let downloadCount = 0;
  let resolveCount = 0;
  const bytes = copyBytes(BASELINE_JPEG);
  const metadata = {
    bytes: bytes.byteLength,
    height: 3,
    mimeType: "image/jpeg",
    sha256: createHash("sha256").update(bytes).digest("hex"),
    width: 2,
  };
  const previousCreateImageBitmap = Object.getOwnPropertyDescriptor(
    globalThis,
    "createImageBitmap",
  );
  Object.defineProperty(globalThis, "createImageBitmap", {
    configurable: true,
    value: async () => ({ close() {}, height: 3, width: 2 }),
    writable: true,
  });

  try {
    const result = await downloadProductImageWithOneAuthRefresh({
      download: async () => {
        downloadCount += 1;
        return downloadCount === 1
          ? new Response(null, { status: 403 })
          : new Response(new Blob([bytes], { type: "image/jpeg" }), {
              status: 200,
            });
      },
      ref: {
        productId: PRODUCT_ID,
        shopId: SHOP_ID,
        variant: "thumb",
        versionId: VERSION_ID,
      },
      resolveSignedRead: async () => {
        resolveCount += 1;
        return {
          cacheScope: "a".repeat(64),
          item: {
            expiresAt: new Date(Date.now() + 300_000).toISOString(),
            metadata,
            productId: PRODUCT_ID,
            signedUrl: `https://example.invalid/read-${resolveCount}`,
            status: "ready",
            variant: "thumb",
            versionId: VERSION_ID,
          },
        };
      },
    });

    assert.equal(downloadCount, 2);
    assert.equal(resolveCount, 2);
    assert.equal(result.blob.type, "image/jpeg");
  } finally {
    if (previousCreateImageBitmap) {
      Object.defineProperty(
        globalThis,
        "createImageBitmap",
        previousCreateImageBitmap,
      );
    } else {
      delete globalThis.createImageBitmap;
    }
  }
});

test("TASK-137 signed read never retries invalid image bytes", async () => {
  let downloadCount = 0;
  let resolveCount = 0;

  await assert.rejects(
    downloadProductImageWithOneAuthRefresh({
      download: async () => {
        downloadCount += 1;
        return new Response(new Blob([Uint8Array.from([1, 2, 3])]), {
          status: 200,
        });
      },
      ref: {
        productId: PRODUCT_ID,
        shopId: SHOP_ID,
        variant: "thumb",
        versionId: VERSION_ID,
      },
      resolveSignedRead: async () => {
        resolveCount += 1;
        return {
          cacheScope: "a".repeat(64),
          item: {
            productId: PRODUCT_ID,
            signedUrl: "https://example.invalid/read",
            status: "ready",
            variant: "thumb",
            versionId: VERSION_ID,
          },
        };
      },
    }),
    /image_download_invalid/,
  );

  assert.equal(downloadCount, 1);
  assert.equal(resolveCount, 1);
});

test("TASK-139 image download rejects an oversized Content-Length before buffering", async () => {
  let bodyCancelled = false;
  const response = new Response(
    new ReadableStream({
      cancel() {
        bodyCancelled = true;
      },
      pull(controller) {
        controller.enqueue(Uint8Array.from([0xff, 0xd8, 0xff, 0xd9]));
      },
    }),
    {
      headers: {
        "content-length": String(PRODUCT_IMAGE_THUMB_MAX_BYTES + 1),
        "content-type": "image/jpeg",
      },
    },
  );

  await assert.rejects(
    downloadProductImageWithOneAuthRefresh({
      download: async () => response,
      ref: {
        productId: PRODUCT_ID,
        shopId: SHOP_ID,
        variant: "thumb",
        versionId: VERSION_ID,
      },
      resolveSignedRead: async () => ({
        cacheScope: "a".repeat(64),
        item: {
          productId: PRODUCT_ID,
          signedUrl: "https://example.invalid/read",
          status: "ready",
          variant: "thumb",
          versionId: VERSION_ID,
        },
      }),
    }),
    /image_download_invalid/,
  );
  assert.equal(bodyCancelled, true);
});

test("TASK-139 image download cancels an unknown-length stream at the byte cap", async () => {
  let cancelled = false;
  let pulls = 0;
  const response = new Response(
    new ReadableStream({
      cancel() {
        cancelled = true;
      },
      pull(controller) {
        pulls += 1;
        controller.enqueue(new Uint8Array(50 * 1024));
      },
    }),
    { headers: { "content-type": "image/jpeg" } },
  );

  await assert.rejects(
    downloadProductImageWithOneAuthRefresh({
      download: async () => response,
      ref: {
        productId: PRODUCT_ID,
        shopId: SHOP_ID,
        variant: "thumb",
        versionId: VERSION_ID,
      },
      resolveSignedRead: async () => ({
        cacheScope: "a".repeat(64),
        item: {
          productId: PRODUCT_ID,
          signedUrl: "https://example.invalid/read",
          status: "ready",
          variant: "thumb",
          versionId: VERSION_ID,
        },
      }),
    }),
    /image_download_invalid/,
  );
  assert.equal(cancelled, true);
  assert.ok(pulls <= 3, `stream pulled ${pulls} chunks past its cap`);
});

test("TASK-137 cleanup selects only aged canonical objects without lifecycle rows", () => {
  const path = `${"shops/10000000-0000-4000-8000-000000000137"}/products/${PRODUCT_ID}/primary/${VERSION_ID}/main.jpg`;
  const cutoffTime = Date.parse("2026-07-17T12:00:00Z");

  assert.equal(isCanonicalProductImageObjectPath(path, SHOP_ID), true);
  assert.equal(
    isEligibleProductImageOrphan(
      { createdAt: "2026-07-16T11:59:59Z", path },
      new Set(),
      cutoffTime,
      SHOP_ID,
    ),
    true,
  );
  assert.equal(
    isEligibleProductImageOrphan(
      { createdAt: "2026-07-16T11:59:59Z", path },
      new Set([path]),
      cutoffTime,
      SHOP_ID,
    ),
    false,
  );
  assert.equal(
    isEligibleProductImageOrphan(
      { createdAt: "2026-07-17T12:00:01Z", path },
      new Set(),
      cutoffTime,
      SHOP_ID,
    ),
    false,
  );
  assert.equal(
    isEligibleProductImageOrphan(
      { createdAt: "2026-07-16T11:59:59Z", path: "unscoped/main.jpg" },
      new Set(),
      cutoffTime,
      SHOP_ID,
    ),
    false,
  );
  assert.equal(
    isEligibleProductImageOrphan(
      { createdAt: "2026-07-16T11:59:59Z", path },
      new Set(),
      cutoffTime,
      "40000000-0000-4000-8000-000000000137",
    ),
    false,
  );
});

test("TASK-137 UI keeps image upload separate from product form and cleanup defaults to dry-run", async () => {
  const [controls, cleanup] = await Promise.all([
    readFile(
      new URL(
        "../../src/app/shop/_components/ProductImageControls.tsx",
        import.meta.url,
      ),
      "utf8",
    ),
    readFile(
      new URL(
        "../../scripts/admin/task-137-product-image-cleanup.mjs",
        import.meta.url,
      ),
      "utf8",
    ),
  ]);

  assert.match(controls, /data-product-image-editor/);
  assert.match(controls, /accept="\.jpg,\.jpeg,\.png,image\/jpeg,image\/png"/);
  assert.doesNotMatch(controls, /<form\b/);
  assert.match(cleanup, /const execute = args\.has\("--execute"\)/);
  assert.match(cleanup, /mode=\$\{execute \? "execute" : "dry-run"\}/);
  assert.match(cleanup, /const batchLimit = 100/);
  assert.match(cleanup, /SHOP_ID_REQUIRED/);
  assert.match(cleanup, /product_image_prepare_cleanup/);
  assert.match(cleanup, /product_image_record_orphan_cleanup/);
  assert.doesNotMatch(cleanup, /console\.log\([^\n]*(main_path|thumb_path)/);
});

test("TASK-137 operational report is bounded, read-only and redacts shop and object paths", async () => {
  const [report, packageJson] = await Promise.all([
    readFile(
      new URL(
        "../../scripts/admin/task-137-product-image-report.mjs",
        import.meta.url,
      ),
      "utf8",
    ),
    readFile(new URL("../../package.json", import.meta.url), "utf8"),
  ]);

  assert.match(packageJson, /"task137:images:report"/);
  assert.match(report, /assertLocalTargetEnv/);
  assert.match(report, /assertStagingTargetEnv/);
  assert.match(report, /const maximumRows = 50_000/);
  assert.match(report, /const maximumStorageObjects = 50_000/);
  assert.match(report, /current_image_count/);
  assert.match(report, /storage_total_bytes/);
  assert.match(report, /unreferenced_object_count/);
  assert.match(report, /above_budget_version_count/);
  assert.match(report, /health_result/);
  assert.match(report, /IMAGE_HEALTH_CHECK_FAILED/);
  assert.match(report, /canonicalObjectPathPattern/);
  assert.match(report, /hashShopId/);
  assert.doesNotMatch(report, /info\([^\n]*(main_path|thumb_path|objectPath)/);
  assert.doesNotMatch(report, /\.(insert|delete|upsert|remove)\s*\(/);
  assert.doesNotMatch(
    report,
    /\.from\([^)]*\)[\s\S]{0,160}\.update\s*\(/,
  );
});
