export const platformShopAuditEvents = {
  createAttempt: "platform.shop.create.attempt",
  createSuccess: "platform.shop.create.success",
  createFailure: "platform.shop.create.failure",
  ownerAssignAttempt: "platform.shop.owner.assign.attempt",
  ownerAssignSuccess: "platform.shop.owner.assign.success",
  ownerAssignFailure: "platform.shop.owner.assign.failure",
  memberAssignAttempt: "platform.shop.member.assign.attempt",
  memberAssignSuccess: "platform.shop.member.assign.success",
  memberAssignFailure: "platform.shop.member.assign.failure",
  memberRevokeAttempt: "platform.shop.member.revoke.attempt",
  memberRevokeSuccess: "platform.shop.member.revoke.success",
  memberRevokeFailure: "platform.shop.member.revoke.failure",
  activateAttempt: "platform.shop.activate.attempt",
  activateSuccess: "platform.shop.activate.success",
  activateFailure: "platform.shop.activate.failure",
  suspendAttempt: "platform.shop.suspend.attempt",
  suspendSuccess: "platform.shop.suspend.success",
  suspendFailure: "platform.shop.suspend.failure",
  reactivateAttempt: "platform.shop.reactivate.attempt",
  reactivateSuccess: "platform.shop.reactivate.success",
  reactivateFailure: "platform.shop.reactivate.failure",
  softDeleteAttempt: "platform.shop.soft_delete.attempt",
  softDeleteSuccess: "platform.shop.soft_delete.success",
  softDeleteFailure: "platform.shop.soft_delete.failure",
  purgeAttempt: "platform.shop.purge.attempt",
  purgeSnapshot: "platform.shop.purge.snapshot",
  purgeSuccess: "platform.shop.purge.success",
  purgeFailure: "platform.shop.purge.failure",
  forcePurgeFailure: "platform.shop.force_purge.failure",
} as const;

export type PlatformShopAuditEvent =
  (typeof platformShopAuditEvents)[keyof typeof platformShopAuditEvents];
