export const platformProvisioningLabelKeys = [
  "Action ready.",
  "Access: full Admin Console access",
  "A provisioning reason is required.",
  "A staff account with this code already exists for the shop.",
  "Address",
  "Attach an active personal profile as shop owner during creation.",
  "Business address is required.",
  "Business city is required.",
  "Business giro",
  "Business giro is required.",
  "Check the required fields and try again.",
  "Choose owner setup.",
  "City",
  "Company RUT",
  "Copied",
  "Copy PIN",
  "Create pending owner setup",
  "Create POS-first shop",
  "Create shop",
  "Create shop with owner",
  "Create shops, fiscal identity, and initial manager access through audited Platform Admin boundaries.",
  "Create the shop and initial manager before linking a personal owner.",
  "Create the shop, fiscal identity, initial manager access, and optional owner setup.",
  "Creating pending owner setup",
  "Creating POS-first shop",
  "Creating shop with owner",
  "Display name: manager",
  "Emergency recovery: recover initial manager 1001",
  "Enter a valid Chilean RUT. You can enter only numbers; for example 123456789.",
  "Existing personal owner",
  "Fiscal / Boleta identity",
  "Fiscal identity is managed by Master Console and shown read-only in Admin Console.",
  "Future owner email",
  "If manager 1001 exists and is usable, recovery resets its PIN. If manager 1001 is suspended, archived, disabled or otherwise not usable, recovery reactivates it and resets its PIN. If manager 1001 is missing, recovery recreates manager 1001 with full access.",
  "Initial manager access",
  "Initial manager recovery found duplicate manager 1001 rows. Manual review is required.",
  "Initial owner",
  "Initial owner is required.",
  "Legal representative RUT",
  "Link existing personal owner",
  "Manager availability is resolved at the server boundary after shop selection. Dynamic manager selection is not available in this read model yet.",
  "Manager permission write failed at the database boundary.",
  "Manager reactivated and PIN reset",
  "Manager recreated",
  "Manager state",
  "New manager display name: manager",
  "No personal owner now / POS-first",
  "No personal owner yet",
  "No profiles match this search",
  "No results.",
  "No shops match this search",
  "None",
  "Not returned",
  "Not returned by this action",
  "Only manager 1001 can be recovered by this action.",
  "Operation result",
  "Owner email is required.",
  "Owner mode",
  "Owner setup",
  "Owner status",
  "Pending owner setup",
  "Pending owner setup recorded",
  "Personal owner linked",
  "PIN reset",
  "POS-first",
  "Ready.",
  "Reason",
  "Reason is required.",
  "Record a pending setup email without activating email delivery.",
  "Record pending owner email",
  "Recover initial manager 1001",
  "Recover manager 1001",
  "Recovering manager 1001",
  "Recovery could not complete because the database boundary failed. Check server diagnostics.",
  "Retail and POS operations",
  "RUT can be typed with or without dots/dash. Shop code uses the compact RUT for login.",
  "RUT can contain numbers and K only as the final check digit.",
  "RUT is required.",
  "Safe provisioning",
  "Save this PIN now. It will not be shown again.",
  "Search profiles",
  "Search target shops",
  "Select a target shop before running recovery.",
  "Select a valid shop.",
  "Selected owner",
  "Selected shop",
  "Server admin runtime is not configured. Recovery cannot update staff credentials in this runtime.",
  "Shop code",
  "Shop code must be 3-32 uppercase letters, numbers, underscore, or dash.",
  "Shop created",
  "Shop identity",
  "Shop name",
  "Shop name is required.",
  "Shop Provisioning",
  "Shown below",
  "Staff account lookup failed at the database boundary.",
  "Staff account write failed at the database boundary.",
  "Staff code",
  "Staff code: 1001",
  "Staff manager web access was provisioned.",
  "Target shop",
  "Temporary PIN. It is shown once after creation and should be changed after first access.",
  "Temporary PIN. Shown once in this response. It will not be shown again.",
  "Temporary PIN shown once",
  "The controlled database action failed without exposing internal details.",
  "The selected shop is inactive or archived.",
  "The selected shop is not eligible for staff manager web access.",
  "This records a pending owner setup. Email delivery is not active yet.",
  "This recovery always targets staff code 1001. Client-provided staff code values are ignored by the server.",
  "Use 2-32 uppercase letters, numbers, dash or underscore.",
  "Use 3-32 uppercase letters, numbers, dash or underscore.",
  "Use Company RUT as Shop code",
  "Use shops as the business root. Shop code remains a technical POS/Admin Console login code; company RUT is stored separately for fiscal/boleta identity.",
  "Use this only when an existing shop lost manager access. The server will restore or recreate manager 1001 and generate a new temporary PIN. The old PIN is never shown.",
  "Use this PIN with shop code and staff code 1001 for the first Admin Console / Win7POS access. The shop should change it after first access.",
  "Why this provisioning action is approved",
] as const;

export type PlatformProvisioningLabels = Record<string, string>;

export function createPlatformProvisioningLabels(
  translate: (value: string) => string,
): PlatformProvisioningLabels {
  return Object.fromEntries(
    platformProvisioningLabelKeys.map((key) => [key, translate(key)]),
  );
}

export const defaultPlatformProvisioningLabels =
  createPlatformProvisioningLabels((value) => value);

export function createPlatformProvisioningTranslator(
  labels: PlatformProvisioningLabels,
) {
  return (value: string) => labels[value] ?? value;
}
